name: Build Web Application on Pull Request
on:
  pull_request:
    branches: [main]
permissions:
  contents: write
  pull-requests: write
jobs:
  build_web_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.1

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: pnpm

      - name: install Dependencies
        working-directory: apps/readest-app
        run: |
          pnpm install && pnpm setup-pdfjs

      - name: build the web App
        working-directory: apps/readest-app
        run: |
          pnpm build-web
